# Permalinks
permalink:           pretty

# Setup
title:               Jakub Chłędowski
url:                 http://chledowski.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jakub Chłędowski
  url:               https://twitter.com/jchledowski
  email:             jakub.chledowski@gmail.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
